- project:
    templates:
      - check-requirements
      - publish-openstack-docs-pti
      - openstack-cover-jobs
    check:
      jobs:
        - openstack-tox-pep8
        - openstack-tox-py35
        - openstack-tox-py36
        - openstack-tox-py37
        - openstack-tox-py38
        - openstack-tox-py39
    gate:
      jobs:
        - openstack-tox-pep8
        - openstack-tox-py35
        - openstack-tox-py36
        - openstack-tox-py37
        - openstack-tox-py38
        - openstack-tox-py39
