- project:
    templates:
      - check-requirements
      - publish-openstack-docs-pti
      - openstack-cover-jobs
    check:
      jobs:
        - openstack-tox-pep8
        - openstack-tox-py39
        - openstack-tox-py310
        - openstack-tox-py311
        - openstack-tox-py312
    gate:
      jobs:
        - openstack-tox-pep8
        - openstack-tox-py39
        - openstack-tox-py310
        - openstack-tox-py311
        - openstack-tox-py312
